### ISSUE TITLE
Large catarium card for the gear construction

### ISSUE THREAD

**Issue by irishwizz** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#54] opened 2018-07-08 15:19 UTC
Aside of the Catarium, all the other cards have a normal size, but the Catarium is huge:

https://zupimages.net/up/18/27/gj3h.jpg

**Comment by KarateSnoopy** [comment] 2018-07-08 19:20
Dupe of https://github.com/maximo1984/Kingdom-Death-Maximo-Kijan-Mod/issues/8

**Closed by KarateSnoopy** 2018-07-08 19:20 UTC
